[workspace]
authors = ["lnotspotl <lnotspotl@gmail.com>"]
channels = ["robostack-staging", "conda-forge",  "robostack-noetic"]
name = "tbai_ros"
platforms = ["linux-64", "linux-aarch64"]
version = "0.0.5"

[feature.common.dependencies]

# tbai dependencies
gxx="13.3.0.*"
gcc="13.3.0.*"
fmt="10.2.1.*"
spdlog="1.13.0.*"
libtorch = { version = "==2.1.0", build = "*cpu_generic*" }
cpp-argparse = "*"
eigen="3.4.0.*"
gtest="*"
pybind11="2.13.6.*"
yaml-cpp="*"
pinocchio="2.7.*"
cmake="3.28.3.*"
huggingface_hub = "*"
catkin_tools = "*"
make = "*"
rosdep = "*"
python="3.11.*"
compilers = "*"
pkg-config = "*"
ninja = "*"

[feature.go2.dependencies]
pcl="*"
ros-noetic-pcl-ros="*"
ros-noetic-desktop="1.5.0.*"
librealsense = ">=2.55.1,<3"

[feature.all.dependencies]
ros-noetic-desktop-full = "1.5.0.*"
gazebo = "11.14.0.*"
ros-distro-mutex = "0.5.0.*"
libprotobuf = "*"
colcon-common-extensions = "*"
doxygen = "*"
ros-noetic-ros-control = "*"
ros-noetic-ros-controllers = "*"
mpfr = "*"
glpk = "*"
ros-noetic-octomap-mapping = "*"
ros-noetic-octomap-server = "*"
librealsense = ">=2.55.1,<3"

[feature.go2-gpu.dependencies]
cuda-version = "11.4.*"
cupy = "*"
ros-noetic-image-transport = ">=1.12.0,<2"
ros-noetic-image-transport-plugins = ">=1.14.0,<2"

[feature.desktop-gpu.dependencies]
cuda-version = "12.8.*"
cupy = "*"
ros-noetic-image-transport = ">=1.12.0,<2"
ros-noetic-image-transport-plugins = ">=1.14.0,<2"

[environments]
all = ["common", "all", "desktop-gpu"]
all-gpu-free = ["common", "all"]
go2 = ["common", "go2", "go2-gpu"]
go2-gpu-free = ["common", "go2"]

[tasks]
ros_init = {cmd = "cd ../.. && rm -rf .catkin_tools && catkin init && catkin config -DCMAKE_BUILD_TYPE=Release" }
clean = { cmd = "cd ../.. && catkin init && catkin config -DCMAKE_BUILD_TYPE=Release && cd $OLDPWD  && catkin clean -y && rm -rf dependencies/tbai" }
remove_tbai = {cmd="rm -rf dependencies/tbai && rm -rf /tmp/cpmbuild"}
clone_tbai = { cmd = "git clone git@github.com:lnotspotl/tbai.git --single-branch --branch=main dependencies/tbai", depends-on=["remove_tbai"] }
build_tbai = { cmd = "cmake -B/tmp/cpmbuild -Sdependencies/tbai -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX && cmake --build /tmp/cpmbuild --parallel 8 && cmake --build /tmp/cpmbuild --target install" }
ros_build_all = { cmd = "./tbai_ros.bash --build && echo 'export GAZEBO_PLUGIN_PATH=$GAZEBO_PLUGIN_PATH:$(catkin locate)/devel/lib:$CONDA_PREFIX/lib' >> ../../devel/setup.sh" }
ros_build_go2 = { cmd = "catkin build tbai_ros_deploy_go2_rl" }

fresh_build_go2 = { cmd = "echo finished ", depends-on = ["clean", "clone_tbai", "build_tbai", "ros_build_go2"] }

fresh_build_all = { cmd = "echo finished " , depends-on = ["clean", "clone_tbai", "build_tbai", "ros_build_all"] }

[dependencies]
python = ">=3.11.8,<3.14"

[pypi-dependencies]
simple-parsing = ">=0.1.7, <0.2"
ruamel-yaml = ">=0.18.14, <0.19"
shapely = ">=2.1.1, <3"
