plugin_config_file: '$(rospack find elevation_mapping_cupy)/config/setups/anymal/anymal_plugin_config.yaml'

pointcloud_channel_fusions:
  rgb: 'color'
  default: 'average'

image_channel_fusions:
  rgb: 'color'
  default: 'exponential'
  feat_.*: 'exponential'
  sem_.*: 'exponential'

#### Publishers ########
# topic_name:
#   layers:               # Choose from 'elevation', 'variance', 'traversability', 'time', 'normal_x', 'normal_y', 'normal_z', 'color', plugin_layer_names
#   basic_layers:         # basic_layers for valid cell computation (e.g. Rviz): Choose a subset of `layers`.
#   fps:                  # Publish rate. Use smaller value than `map_acquire_fps`.

publishers:
  elevation_map_raw:
    layers: ['elevation', 'inpaint']
    basic_layers: ['inpaint']
    fps: 5.0

  elevation_map_recordable:
    layers: ['elevation', 'inpaint']
    basic_layers: ['inpaint']
    fps: 2.0

#### Subscribers ########
subscribers:
  front_upper_depth:
    topic_name: /camera/depth/points
    data_type: pointcloud
